# Generated by Django 5.0.4 on 2024-04-22 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_blog_title_alter_category_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogimage',
            name='image',
            field=models.FileField(default='blank_image.jpg', upload_to='blog_images/'),
        ),
    ]
