# Generated by Django 5.0.4 on 2024-04-22 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_blogimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='blank_image.jpg', null=True, upload_to='blog_single_image/'),
        ),
        migrations.AlterField(
            model_name='blogimage',
            name='image',
            field=models.FileField(upload_to='blog_images/'),
        ),
    ]
